name: Build and push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        docker build -t docker.pkg.github.com/andrchalov/ansible-action/app:latest .
        docker push docker.pkg.github.com/andrchalov/ansible-action/app:latest
