name: Build and push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/app:latest .
        docker login docker.pkg.github.com --username andrchalov --password $DOCKER_TOKEN
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/app:latest
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
